import { Genres_NT } from 'types';

export const GENRES_NT: Genres_NT[] = [
    { id: '1', value: 'action', label: 'Action' },
    { id: '3', value: 'adventure', label: 'Adventure' },
    { id: '4', value: 'anime', label: 'Anime' },
    { id: '5', value: 'chuyen-sinh-213', label: 'Chuyển sinh' },
    { id: '6', value: 'comedy-99', label: 'Comedy' },
    { id: '7', value: 'comic', label: 'Comic' },
    { id: '8', value: 'cooking', label: 'Cooking' },
    { id: '9', value: 'co-dai-207', label: 'Cổ đại' },
    { id: '10', value: 'doujinshi', label: 'Doujinshi' },
    { id: '11', value: 'drama-103', label: 'Drama' },
    { id: '12', value: 'dam-my', label: 'Đam mỹ' },
    { id: '13', value: 'ecchi', label: 'Ecchi' },
    { id: '14', value: 'fantasy-105', label: 'Fantasy' },
    { id: '16', value: 'harem-107', label: 'Harem' },
    { id: '17', value: 'historical', label: 'Historical' },
    { id: '18', value: 'horror', label: 'Horror' },
    { id: '20', value: 'josei', label: 'Josei' },
    { id: '21', value: 'live-action', label: 'Live action' },
    { id: '23', value: 'manga-112', label: 'Manga' },
    { id: '24', value: 'manhua', label: 'Manhua' },
    { id: '25', value: 'manhwa-11400', label: 'Manhwa' },
    { id: '10', value: 'doujinshi', label: 'Doujinshi' },
    { id: '26', value: 'martial-arts', label: 'Martial Arts' },
    { id: '27', value: 'mature', label: 'Mature' },
    { id: '28', value: 'mecha-117', label: 'Mecha' },
    { id: '32', value: 'ngon-tinh', label: 'Ngôn tình' },
    { id: '33', value: 'one-shot', label: 'One shot' },
    { id: '34', value: 'psychological', label: 'Psychological' },
    { id: '35', value: 'romance-121', label: 'Romance' },
    { id: '36', value: 'school-life', label: 'School Life' },
    { id: '37', value: 'sci-fi', label: 'Sci-fi' },
    { id: '38', value: 'seinen', label: 'Seinen' },
    { id: '39', value: 'shoujo', label: 'Shoujo' },
    { id: '40', value: 'shoujo-ai-126', label: 'Shoujo Ai' },
    { id: '41', value: 'shounen-127', label: 'Shounen' },
    { id: '42', value: 'shounen-ai', label: 'Shounen Ai' },
    { id: '43', value: 'slice-of-life', label: 'Slice Of Life' },
    { id: '58', value: 'yaoi', label: 'Yaoi' },
    { id: '45', value: 'soft-yaoi', label: 'Soft Yaoi' },
    { id: '59', value: 'yuri', label: 'Yuri' },
    { id: '46', value: 'soft-yuri', label: 'Soft Yuri' },
    { id: '47', value: 'sports', label: 'Sports' },
    { id: '48', value: 'supernatural', label: 'Supernatural' },
    { id: '44', value: 'smut', label: 'Smut' },
    { id: '49', value: 'tap-chi-truyen-tranh', label: 'Tạp chí truyện tranh' },
    { id: '50', value: 'thieu-nhi', label: 'Thiếu nhi' },
    { id: '51', value: 'tragedy-136', label: 'Tragedy' },
    { id: '52', value: 'trinh-tham', label: 'Trinh thám' },
    { id: '54', value: 'truyen-scan', label: 'Truyện Scan' },
    { id: '53', value: 'truyen-mau', label: 'Truyện màu' },
    { id: '55', value: 'viet-nam', label: 'Việt Nam' },
    { id: '56', value: 'webtoon', label: 'Webtoon' },
    { id: '57', value: 'xuyen-khong-205', label: 'Xuyên không' },
    { id: '60', value: '16', label: '16+' },
    { id: '2', value: 'truong-thanh', label: 'Trưởng thành' },
];
